### ISSUE TITLE
Could you please provide the specific code

### ISSUE THREAD

**Issue by chenpeng052** [eashanadhikarla/ExpoMamba#1]
Could you please provide the specific code

**Comment by eashanadhikarla** [comment]
Thank you Chen Peng for your interest in our research paper. The code will be released on Sept 1, 2024 (end of this week)

**Comment by baiyu001** [comment]
> Thank you Chen Peng for your interest in our research paper. The code will be released on Sept 1, 2024 (end of this week)

Hello, this is a very great research work and I have been following it, when could you please open the source code ?

**Comment by eashanadhikarla** [comment]
@baiyu001 I have released the model definition and simultaneously working on releasing other files.  I will try my best to release sufficient details sooner.

**Comment by baiyu001** [comment]
> @baiyu001 I have released the model definition and simultaneously working on releasing other files. I will try my best to release sufficient details sooner.

Ok, thank you very much.
